### ISSUE TITLE
Lack of ability to reconnect

### ISSUE THREAD

**Issue by Crozin** [Recognos/Metrics.NET.Graphite#1]
Hello.
It seems that Metrics.NET is not capable of reconnecting to Graphite server in case of connection loss. This of course leads missing metrics and forces us to restart entire application in order to reconnect. Is there any chance fix this issue?

**Comment by Kanatovich** [comment]
If you use TCP transport Metrics.NET.Graphite able to reconnect, look at [https://github.com/Recognos/Metrics.NET.Graphite/blob/dev/Src/Metrics.NET.Graphite/TcpGraphiteSender.cs#L40](url) 
For proper configuration of Metrics.NET try to look at [https://github.com/Recognos/Metrics.NET/issues/53](url)

**Comment by Crozin** [comment]
Hey.
I found `Metrics.Reports.ToleratedConsecutiveFailures` some time ago. Thanks for answering anyway. :)
