### ISSUE TITLE
Promotion to stable status in nuget

### ISSUE THREAD

**Issue by jongear** [Recognos/Metrics.NET.Graphite#2]
Is there a timeline for this project to be migrated into a stable nuget release?  Being a prelease, this package causes nuget package retrievals when adding new packages that rely on `Metrics.NET.Graphite`.  This can be reconciled by hand but it would be nice to have a stable package.

**Comment by jongear** [comment]
@PaulParau is this project still maintained?

**Comment by PaulParau** [comment]
@jongear I've released a stable version, sorry for the delay. Yes, our aim is to continue to maintain this project.

**Comment by jongear** [comment]
Awesome, thanks Paul!
